# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pagerank_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16pagerank_service.proto\x12\x11\x64ocumentprocessor\"C\n\x0f\x44ocumentRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x0e\n\x06\x63licks\x18\x03 \x03(\x05\"?\n\x10\x44ocumentResponse\x12\x14\n\x0c\x64ocumentName\x18\x01 \x01(\t\x12\x15\n\rpageRankScore\x18\x02 \x01(\x01\"F\n\x0c\x44ocumentList\x12\x36\n\tdocuments\x18\x01 \x03(\x0b\x32#.documentprocessor.DocumentResponse2l\n\x11\x44ocumentProcessor\x12W\n\x10ProcessDocuments\x12\".documentprocessor.DocumentRequest\x1a\x1f.documentprocessor.DocumentListB Z\x1eLDA_PageRank_Query/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pagerank_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036LDA_PageRank_Query/proto;proto'
  _globals['_DOCUMENTREQUEST']._serialized_start=45
  _globals['_DOCUMENTREQUEST']._serialized_end=112
  _globals['_DOCUMENTRESPONSE']._serialized_start=114
  _globals['_DOCUMENTRESPONSE']._serialized_end=177
  _globals['_DOCUMENTLIST']._serialized_start=179
  _globals['_DOCUMENTLIST']._serialized_end=249
  _globals['_DOCUMENTPROCESSOR']._serialized_start=251
  _globals['_DOCUMENTPROCESSOR']._serialized_end=359
# @@protoc_insertion_point(module_scope)
